from pathlib import Path

from pydantic import BaseModel, Field

from agent import CompanyProfile
from strategy import BusinessStrategy


# ============================================================
# FINAL REPORT SCHEMA
# ============================================================

class FinalReport(BaseModel):
    company_profile: CompanyProfile
    business_strategy: BusinessStrategy


# ============================================================
# FINAL REPORT VALIDATION
# ============================================================

def validate_final_report(
    report: FinalReport,
) -> tuple[bool, list[str]]:

    issues = []

    profile = report.company_profile
    strategy = report.business_strategy

    # --------------------------------------------------------
    # Company profile
    # --------------------------------------------------------

    required_company_fields = [
        "company_name",
        "industry",
        "description",
        "offer",
        "target_audience",
        "problem_solved",
        "business_model",
    ]

    for field in required_company_fields:

        value = getattr(
            profile,
            field,
            None,
        )

        if not value or not str(value).strip():
            issues.append(
                f"Company profile field is empty: {field}"
            )

    # --------------------------------------------------------
    # Evidence
    # --------------------------------------------------------

    if len(profile.evidence) < 3:
        issues.append(
            "Final report contains fewer than 3 evidence items."
        )

    source_urls = set()

    for index, evidence in enumerate(
        profile.evidence,
        start=1,
    ):

        if not evidence.source_url:
            issues.append(
                f"Evidence item {index} has no source URL."
            )

        if evidence.source_url in source_urls:
            issues.append(
                f"Duplicate evidence URL found: "
                f"{evidence.source_url}"
            )

        source_urls.add(
            evidence.source_url
        )

        if not evidence.claim.strip():
            issues.append(
                f"Evidence item {index} has an empty claim."
            )

    # --------------------------------------------------------
    # Strategy sections
    # --------------------------------------------------------

    if not strategy.marketing_observations:
        issues.append(
            "Final report has no marketing observations."
        )

    if not strategy.lead_generation_opportunities:
        issues.append(
            "Final report has no lead generation opportunities."
        )

    if not strategy.automation_opportunities:
        issues.append(
            "Final report has no automation opportunities."
        )

    if not strategy.recommended_actions:
        issues.append(
            "Final report has no recommended actions."
        )

    # --------------------------------------------------------
    # Evidence attached to recommendations
    # --------------------------------------------------------

    for index, opportunity in enumerate(
        strategy.lead_generation_opportunities,
        start=1,
    ):

        if not opportunity.supporting_evidence:
            issues.append(
                f"Lead generation opportunity {index} "
                "has no supporting evidence."
            )

    for index, opportunity in enumerate(
        strategy.automation_opportunities,
        start=1,
    ):

        if not opportunity.supporting_evidence:
            issues.append(
                f"Automation opportunity {index} "
                "has no supporting evidence."
            )

    return (
        len(issues) == 0,
        issues,
    )


# ============================================================
# BUILD FINAL REPORT
# ============================================================

def build_final_report(
    company_profile: CompanyProfile,
    business_strategy: BusinessStrategy,
) -> FinalReport:

    return FinalReport(
        company_profile=company_profile,
        business_strategy=business_strategy,
    )


# ============================================================
# MARKDOWN REPORT
# ============================================================

def render_markdown_report(
    report: FinalReport,
) -> str:

    profile = report.company_profile
    strategy = report.business_strategy

    lines = []

    # --------------------------------------------------------
    # Header
    # --------------------------------------------------------

    lines.extend([
        f"# {profile.company_name} — Business Strategy Report",
        "",
        "> Generated by BusinessIntel AI",
        "",
        "---",
        "",
    ])

    # --------------------------------------------------------
    # Company overview
    # --------------------------------------------------------

    lines.extend([
        "## 1. Company Overview",
        "",
        f"**Company:** {profile.company_name}",
        "",
        f"**Industry:** {profile.industry}",
        "",
        f"**Description:** {profile.description}",
        "",
    ])

    # --------------------------------------------------------
    # Offer
    # --------------------------------------------------------

    lines.extend([
        "## 2. Offer",
        "",
        profile.offer,
        "",
    ])

    # --------------------------------------------------------
    # Target audience
    # --------------------------------------------------------

    lines.extend([
        "## 3. Target Audience",
        "",
        profile.target_audience,
        "",
    ])

    # --------------------------------------------------------
    # Problem solved
    # --------------------------------------------------------

    lines.extend([
        "## 4. Problem Solved",
        "",
        profile.problem_solved,
        "",
    ])

    # --------------------------------------------------------
    # Business model
    # --------------------------------------------------------

    lines.extend([
        "## 5. Business Model",
        "",
        profile.business_model,
        "",
    ])

    # --------------------------------------------------------
    # Marketing observations
    # --------------------------------------------------------

    lines.extend([
        "## 6. Marketing Observations",
        "",
    ])

    for index, item in enumerate(
        strategy.marketing_observations,
        start=1,
    ):

        lines.extend([
            f"### {index}. {item.observation}",
            "",
            f"**Implication:** {item.implication}",
            "",
        ])

        if item.supporting_evidence:

            lines.append(
                "**Supporting evidence:**"
            )

            lines.append("")

            for evidence in item.supporting_evidence:
                lines.append(
                    f"- {evidence}"
                )

            lines.append("")

    # --------------------------------------------------------
    # Lead generation
    # --------------------------------------------------------

    lines.extend([
        "## 7. Lead Generation Opportunities",
        "",
    ])

    for index, item in enumerate(
        strategy.lead_generation_opportunities,
        start=1,
    ):

        lines.extend([
            f"### {index}. {item.opportunity}",
            "",
            f"**Rationale:** {item.rationale}",
            "",
            f"**Suggested approach:** {item.suggested_approach}",
            "",
        ])

        if item.supporting_evidence:

            lines.append(
                "**Supporting evidence:**"
            )

            lines.append("")

            for evidence in item.supporting_evidence:
                lines.append(
                    f"- {evidence}"
                )

            lines.append("")

    # --------------------------------------------------------
    # Automation
    # --------------------------------------------------------

    lines.extend([
        "## 8. Automation Opportunities",
        "",
    ])

    for index, item in enumerate(
        strategy.automation_opportunities,
        start=1,
    ):

        lines.extend([
            f"### {index}. {item.process}",
            "",
            f"**Automation idea:** {item.automation_idea}",
            "",
            f"**Expected benefit:** {item.expected_benefit}",
            "",
        ])

        if item.supporting_evidence:

            lines.append(
                "**Supporting evidence:**"
            )

            lines.append("")

            for evidence in item.supporting_evidence:
                lines.append(
                    f"- {evidence}"
                )

            lines.append("")

    # --------------------------------------------------------
    # Recommended actions
    # --------------------------------------------------------

    lines.extend([
        "## 9. Recommended Actions",
        "",
    ])

    for index, item in enumerate(
        strategy.recommended_actions,
        start=1,
    ):

        lines.extend([
            f"### {index}. {item.action}",
            "",
            f"**Why:** {item.reason}",
            "",
            f"**Expected outcome:** {item.expected_outcome}",
            "",
        ])

    # --------------------------------------------------------
    # Sources
    # --------------------------------------------------------

    lines.extend([
        "## 10. Sources & Evidence",
        "",
    ])

    for index, evidence in enumerate(
        profile.evidence,
        start=1,
    ):

        lines.extend([
            f"### Source {index}",
            "",
            f"**{evidence.source_title}**",
            "",
            f"URL: {evidence.source_url}",
            "",
            f"Claim: {evidence.claim}",
            "",
        ])

    return "\n".join(lines)


# ============================================================
# SAVE REPORT
# ============================================================

def save_markdown_report(
    report: FinalReport,
    output_path: str = "business_report.md",
) -> Path:

    markdown = render_markdown_report(
        report
    )

    path = Path(output_path)

    path.write_text(
        markdown,
        encoding="utf-8",
    )

    return path